### ISSUE TITLE
Add orWhereFuzzy search option

### ISSUE THREAD

**Issue by dark4ce** [mattkingshott/quest#2]
Hi, 

Was looking for a replacement for Searchy and came across your implementation. 
In my use case, I need an orWhereFuzzy, so that the query returns results having at least one relevance index > 0  as opposed to having all of them > 0.

Tried contributing but need access.

I have attached the needed changes here if you are kind enough to include them.
[orWhereFuzzy.zip](https://github.com/mattkingshott/quest/files/7295705/orWhereFuzzy.zip)

Thank you,
Catalin Nita.

**Comment by mattkingshott** [comment]
Hi Catalin,

That all sounds very intriguing. I'd be interested in seeing what you come up with, so feel free to show me something when you feel it's ready :)

Best,
Matt

**Comment by dark4ce** [comment]
Hi Matt,

Sorry for being off, but had some health issues I needed to attend. 
The issues you listed above are valid and I will have a look soon to address them.

Thank you,
Catalin.

**Comment by mattkingshott** [comment]
No problem. Hope all is okay with you.

**Comment by dark4ce** [comment]
Hi Matt,

I'm ok now, thank you.
Looked over the issues:
1.  I have now updated the order by fuzzy class so that we can still use it (there might be a time when we have the same score on the total columns, but want to differentiate, to give priority to one)
2. Updated to use query builder
3. Actually removed ->getQuery() after query builder class update
4. Added new test cases for the updates

Can you grant me access to create a pull request as it comes much easier for me than zip archives 

Thank you,
Catalin Nita.

**Comment by mattkingshott** [comment]
Hi Catalin,

You should be able to create a PR. Can you fork the project, then make changes and submit a PR back to the main repo?

**Comment by dark4ce** [comment]
Hi,

Done! Let me know if anything else pops out. You can also make whatever changes you feel like.

Thanks,
Catalin.

**Comment by mattkingshott** [comment]
All merged in. Thanks!

**Comment by mattkingshott** [comment]
Released as version 2

**Comment by dark4ce** [comment]
Cool, thank you!
